# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_page_leave_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='jubmotron_bg_color',
            field=models.CharField(default='#eeeeee', max_length=7),
        ),
        migrations.AddField(
            model_name='page',
            name='jubmotron_text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
