# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170320_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='jubmotron_bg_color',
            new_name='jumbotron_bg_color',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='jubmotron_text_color',
            new_name='jumbotron_text_color',
        ),
    ]
